# Generated by Django 4.1.7 on 2023-04-04 17:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceBump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(default='unknown', max_length=100)),
                ('city', models.CharField(default='Almaty', editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoadCrack',
            fields=[
                ('id_station', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(default='unknown', max_length=100)),
                ('city', models.CharField(default='Almaty', editable=False, max_length=50)),
                ('danger_level', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], default='l', max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('requested_amount', models.IntegerField(default=1)),
            ],
        ),
    ]
